//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VelibGateway_ClientConsole.VelibServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VelibServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/testConnexion", ReplyAction="http://tempuri.org/IService/testConnexionResponse")]
        string testConnexion(string clientID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/testConnexion", ReplyAction="http://tempuri.org/IService/testConnexionResponse")]
        System.Threading.Tasks.Task<string> testConnexionAsync(string clientID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/help", ReplyAction="http://tempuri.org/IService/helpResponse")]
        string help();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/help", ReplyAction="http://tempuri.org/IService/helpResponse")]
        System.Threading.Tasks.Task<string> helpAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : VelibGateway_ClientConsole.VelibServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<VelibGateway_ClientConsole.VelibServiceReference.IService>, VelibGateway_ClientConsole.VelibServiceReference.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string testConnexion(string clientID) {
            return base.Channel.testConnexion(clientID);
        }
        
        public System.Threading.Tasks.Task<string> testConnexionAsync(string clientID) {
            return base.Channel.testConnexionAsync(clientID);
        }
        
        public string help() {
            return base.Channel.help();
        }
        
        public System.Threading.Tasks.Task<string> helpAsync() {
            return base.Channel.helpAsync();
        }
    }
}
